name: Continuous Delivery

on:
  push:
  release:
    types: [published]

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        with:
          package-dir: python_bindings
        env:
          CIBW_SKIP: "*-win32 cp3{6,7,8}-* pp*-* *_i686"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nmslib_metabrainz-wheels-${{ runner.os }}
          path: wheelhouse/*.whl

  build_wheels_macos:
    name: Build wheels on macos-latest (Python ${{ matrix.python-version }})
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12' ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheels
        run: |
          pip3 install -r dev-requirements.txt
          python3 setup.py build_ext
          pip3 wheel . -w wheelhouse
        env:
          CFLAGS: '-mavx'
        working-directory: python_bindings

      - name: Test wheels
        run: |
          pip3 install nmslib-metabrainz --no-index -f wheelhouse
          python3 -m pytest tests/bindings_test.py
        working-directory: python_bindings

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nmslib_metabrainz-wheels-macos-python-${{ matrix.python-version }}
          path: python_bindings/wheelhouse/nmslib*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build python_bindings --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: nmslib_metabrainz-sdist
          path: python_bindings/dist/*.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: [build_wheels, build_sdist, build_wheels_macos]
    environment:
      name: pypi
      url: https://pypi.org/p/nmslib-metabrainz
    permissions:
      id-token: write  # required for PyPI upload
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: nmslib_metabrainz-*
          path: dist/
          merge-multiple: true
      - name: Prepare distributions
        run: |
          ls -l dist/
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags/')

